# Site settings
title: Electrician Iasi
email: pauldobos6@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Ai nevoie de servicii electrice profesionale şi de încredere?"
keywords: "electrcian, electrician iasi, reparatii electrice iasi, iasi elecric, inginer electric iasi"
skills: "Electrician"
meta_author: Paul Dobos

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/profile.php?id=61558441614805
  - title: whatsapp
    url: https://l.facebook.com/l.php?u=https%3A%2F%2Fapi.whatsapp.com%2Fsend%3Fphone%3D%252B40743621852%26app%3Dfacebook%26entry_point%3Dpage_cta%26fbclid%3DIwZXh0bgNhZW0CMTAAAR3vgpQpjSp6NJfSe_qwj2i7e3FB4EdsG57_ogidQ88w8k5kU326Fu-9WdI_aem_Aawdeklr2JqTKWuAUOLOfJlKYQtFaL7L9DiJiFRAkqFpQ8LfcP4m0ApdZaCQosfdboxUQeXR2LXnOvcQWFdqTXyV&h=AT3lZWUsiK7QgxnKmh4XAbfs3eAsrACT_5f40e-TXgi4s0iyvV8Kt1OEW9R3uraS5IAfwb8vhyN9YBG_D2fXOnBiYeEpkB4iK_n6JiOBkDfSW5bY9HADQsBPbeuHEw

# Postal address (add as many lines as necessary)
address:
  - line: Iasi Romania
  - line: De discutat

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
